name: osamh_encryptor
description: "Securely encrypt/decrypt data in your Flutter app using native code. Add random salt and IV for enhanced security. Easy-to-use API, cross-platform compatible."
version: 1.0.4
homepage: https://github.com/subhashDev11/native_encryptor

environment:
  sdk: ^3.5.4
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  web: ^1.1.0
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:

  plugin:
    platforms:
      android:
        package: com.example.native_encryptor
        pluginClass: NativeEncryptorPlugin
      ios:
        pluginClass: NativeEncryptorPlugin
      macos:
        pluginClass: NativeEncryptorPlugin

screenshots:
  - description: 'This is shows the encrypted result.'
    path: screenshots/encrypted_value.png
  - description: 'This is shows the decrypted result.'
    path: screenshots/decrypted_value.png
  - description: 'This is shows the input area.'
    path: screenshots/input_content.png

topics:
  - native-encrypt-decrypt-plugin
  - encryption
  - decryption
  - encryption-decryption-with-salt
  - swift-java-encryption-decryption
